# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'

    - run: git clone --branch shared https://github.com/franciscojma86/plugins.git --depth 1 ../plugins
    - run: touch .env
    - run: dart --version
    - run: flutter --version
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test
